package com.helper.west2ol.fzuhelper.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.helper.west2ol.fzuhelper.bean.CourseBean;
import com.helper.west2ol.fzuhelper.bean.FDScore;
import com.helper.west2ol.fzuhelper.bean.User;

import com.helper.west2ol.fzuhelper.dao.CourseBeanDao;
import com.helper.west2ol.fzuhelper.dao.FDScoreDao;
import com.helper.west2ol.fzuhelper.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseBeanDaoConfig;
    private final DaoConfig fDScoreDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CourseBeanDao courseBeanDao;
    private final FDScoreDao fDScoreDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseBeanDaoConfig = daoConfigMap.get(CourseBeanDao.class).clone();
        courseBeanDaoConfig.initIdentityScope(type);

        fDScoreDaoConfig = daoConfigMap.get(FDScoreDao.class).clone();
        fDScoreDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        courseBeanDao = new CourseBeanDao(courseBeanDaoConfig, this);
        fDScoreDao = new FDScoreDao(fDScoreDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(CourseBean.class, courseBeanDao);
        registerDao(FDScore.class, fDScoreDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        courseBeanDaoConfig.clearIdentityScope();
        fDScoreDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CourseBeanDao getCourseBeanDao() {
        return courseBeanDao;
    }

    public FDScoreDao getFDScoreDao() {
        return fDScoreDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
